protected/models/User.php
<?php
class User extends ActiveRecord
{
    const STATUS_ENABLED  = 1;
    const STATUS_DISABLED = 0;

    const ROLE_ADMIN = 'admin';

    public $id;
    public $display_name;
    public $email;
    public $password;
    public $salt;
    public $status;
    public $roles = array();
    public $created;
    public $updated;
    public $last_login;
    public $last_ip;

    /**
     * Cache of Users fetched by User::getUser($pk);
     *
     * @var array [$pk: $user]
     */
    private static $_users;

    public function rules()
    {
        return array(
            array('email, display_name', 'required'),
            array('email', 'email'),
            array('email', 'unique'),
            array('password', 'required', 'on' => 'insert, updatePassword'),
            // Password must contain at least one letter, at least one number,
            // and be longer than six charaters
            array('password', 'match', 'pattern' => '/^(?=.*[0-9]+.*)(?=.*[a-zA-Z]+.*)[0-9a-zA-Z]{6,}$/',
                'on' => 'insert',
                'message' => 'Password must contain at least one letter, at '
                            .'least one number, and be longer than six charaters'),
            array('password', 'filter',   'filter' => array($this, 'hashPassword'),
                'on' => 'insert, updatePassword'),
            array('salt, created, updated, last_login, last_ip', 'unsafe'),
            array('status', 'in',      'range' => self::getConstants('STATUS_')),
            array('status', 'default', 'value' => self::STATUS_ENABLED),
            array('display_name', 'length', 'max' => 60),
            array('display_name', 'unique'),
            array('roles', 'safe'),
        );
    }

    public function behaviors()
    {
        return array(
            'CTimestampBehavior' => array(
                'class'             => 'zii.behaviors.CTimestampBehavior',
                'createAttribute'   => 'created',
                'updateAttribute'   => 'updated',
                'setUpdateOnCreate' => false,
            ),
            'JsonFieldBehavior' => array(
                'class' => 'JsonFieldBehavior',
                'fields' => array(
                    'roles',
                ),
            ),
        );
    }

    public function relations()
    {
        return array(
            'aliases'   => array(self::HAS_MANY, 'User_Alias',   'user_id'),
            '_projects' => array(self::HAS_MANY, 'Project_User', 'user_id'),
            'settings'  => array(self::HAS_MANY, 'User_Setting', 'user_id'),
            'comments'  => array(self::HAS_MANY, 'Comment',      'user_id'),
        );
    }

    public function attributeLabels()
    {
        return array(
            'status'  => 'Enabled',
            'last_ip' => 'Last IP Address',
            'roles'   => 'Permissions',
        );
    }

    public function afterSave()
    {
        if ($this->isNewRecord) {
            foreach (explode(',', User_Setting::DEFAULT_ON_SETTINGS) as $setting) {
                $model          = new User_Setting;
                $model->user_id = $this->id;
                $model->setting = trim($setting);
                $model->value   = true;
                $model->save();
            }
        }
    }

    public function delete() {
        foreach ($this->projects as $project) {
            $project->delete();
        }
        foreach ($this->settings as $setting) {
            $setting->delete();
        }
        foreach ($this->aliases as $alias) {
            $alias->delete();
        }
        foreach ($this->comments as $comment) {
            $comment->delete();
        }
        parent::delete();
    }

    /**
     * Hashes a plain-text version of password for storage or authentication.
     * This method will also generate a user-salt if one does not already exist.
     *
     * @param string $password plain-text version of password
     */
    public function hashPassword($password)
    {
        // ensure user's salt exists and is not empty
        if (empty($this->salt))
        {
            $this->salt = substr(md5(microtime(TRUE)), 0, 10);
            // don't auto-save if user is a new record (there will obviously be
            // a $this->save() coming right after this is done).
            if (!$this->isNewRecord)
                $this->update(array('salt'));
        }
        $siteSalt = Setting::get('system.salt');
        return sha1($siteSalt . $password . $this->salt);
    }

    /**
     * Shortcut to find a User by an alias
     *
     * @param string $alias
     * @return User|null
     */
    public function findByAlias($alias)
    {
        $this->with('aliases');
        foreach (func_get_args() as $arg) {
            $this->getDbCriteria()
                 ->addSearchCondition('alias', $arg, true, 'OR');
        }
        return $this->find();
    }

    /**
     * Helper function to fetch user by various means.
     *
     * @param string|int $pk Can be a user_id, email, or alias.  Default:
     *                       Yii::app()->user->getUser() will be used.
     * @return User or null if no User is found
     */
    public static function getUser($pk = null, $createIfEmpty = false)
    {
        // cached
        if (!empty(self::$_users[$pk]))
            return self::$_users[$pk];

        // logged-in user
        if (null === $pk && Yii::app()->hasComponent('user')) {

            return ! Yii::app()->user->isGuest
                   ? Yii::app()->user->getUser()
                   : null;
        }

        // user_id
        if (is_numeric($pk)) {
            return self::model()->findByPk($pk);
        }

        // email
        if (is_scalar($pk) && false !== strpos($pk, '@')) {
            $user = self::model()->findByAttributes(array(
                'email' => $pk,
            ));
            if (!empty($user)) {
                self::$_users[$pk] = $user;
                return $user;
            }
        }

        // alias
        $user = self::model()->findByAlias($pk);

        // create if empty toggle
        if ($createIfEmpty) {
            $user = new User;
        }

        self::$_users[$pk] = $user;

        return $user;
    }

    /**
     * RBAC for editing a User
     *
     * @param User $user
     * @return boolean
     */
    public function canEdit(User $user = null)
    {
        if (null === $user && Yii::app()->hasComponent('user')) {
            $user = self::getUser();
        }

        return ($this->id == $user->id);
    }
    
    public function canEditAlias(User $user = null)
    {
        return $this->canEdit($user);
    }

    /**
     * Override to allow projects to be ran through self::setProjects() instead
     *
     * @param array $values
     * @param boolean $safeOnly Default: true
     * @return null
     */
    public function setAttributes($values, $safeOnly = true) {
        if (array_key_exists('projects', $values)) {
            $this->setProjects($values['projects']);
            unset($values['projects']);
        }
        return parent::setAttributes($values, $safeOnly);
    }

    /**
     * Helper to convert an array of project mappings to an array of Pproject models
     *
     * @return array of Project models
     */
    public function getProjects()
    {
        $projects = array();
        foreach ($this->_projects as $project_map) {
            $projects[$project_map->project->name] = $project_map->project;
        }
        return $projects;
    }

    public function setProjects($value)
    {
        Project_User::model()->deleteAllByAttributes(array(
            'user_id' => $this->id,
        ));
        if (is_array($value)) {
            foreach ($value as $project_name) {
                $map = new Project_User;
                $map->user_id = $this->id;
                $map->project_name = $project_name;
                $map->save();
            }
        }
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria=new CDbCriteria;

//    public $id;
//    public $display_name;
//    public $email;
//    public $password;
//    public $salt;
//    public $status;
//    public $roles = array();
//    public $created;
//    public $updated;
//    public $last_login;
//    public $last_ip;

        foreach (array(
            'display_name',
            'email',
            'status',
            'roles',
        ) as $key) {
            $criteria->compare($key, $this->{$key}, true);
        }

        return new CActiveDataProvider(get_class($this), array(
            'criteria'   => $criteria,
            'pagination' => array(
                'pageSize' => 5
            ),
        ));
    }

    /**
     * Retrieves the value of a setting, or $default if not found
     * @param string $name
     * @param mixed $default
     * @return mixed
     */
    public function getSetting($name, $default = null)
    {
        foreach ($this->settings as $setting) {
            if ($name === $setting->setting) {
                return $setting->value;
            }
        }
        return $default;
    }
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
    public $defaultAction = 'list';

    public function actionList()
    {
        $this->view->users = User::model();
    }

    public function actionView($id = null)
    {
        if (null === $id) {
            $id = Yii::app()->user->id;
        }

        $user = $this->loadModel($id);

        $this->view->comments = Comment::model()
                ->newestFirst()
                ->ofUser($user)
                ->limit(3)
                ->findAll();
    }

    public function actionCreate()
    {
        $user = $this->view->user = $this->_update(new User);
        if (!$user->isNewRecord && !$user->hasErrors()) {
            Yii::app()->user->setFlash('success', 'User has been created.');
            $this->redirect(array('user/view', 'id' => $user->primaryKey));
        }
    }

    public function actionUpdate($id = null)
    {
        if (empty($id))
            $id = Yii::app()->user->id;
        
        $user = $this->loadModel($id);

        if (empty($_POST))
            return;

        if (!empty($_POST['User']['password']))
            $user->scenario = 'updatePassword';

        $user = $this->_update($user);
        if (!$user->hasErrors()) {
            Yii::app()->user->setFlash('success', 'Your changes have been saved.');
            $this->redirect(array('user/view', 'id' => $id), 303);
        } else {
            Yii::app()->user->setFlash('error', print_r($user->errors, true));
        }


    }

    /**
     * Updates a model's attributes from $_POST and saves it.
     *
     * @param  User $model
     * @return User
     */
    private function _update($model)
    {
        if (!empty($_POST[get_class($model)])) {
            $model->attributes = $_POST[get_class($model)];
            $model->save();
            // make sure there's always at least one admin
            if (1 == User::model()->count()
                && (!is_array($model->roles)
                    || !in_array(User::ROLE_ADMIN, $model->roles))) {
                Yii::app()->user->setFlash('info',
                    'Admin role was forced onto this user so that there is at least one Admin on the site.');
                $model->roles = array(User::ROLE_ADMIN);
                $model->save();
            }
        }

        return $model;
    }

    public function actionDelete($id)
    {
        if (!Yii::app()->request->isPostRequest)
            throw new CHttpException(400);

        $user = $this->loadModel($id, array('assertPost' => true));
        if (!$user)
            throw new CHttpException(404);
        else
            $user->delete();

        $this->redirect(array('user/list'), 303);
    }

    public function actionAddAlias($id = null)
    {
        if (null === $id)
            $id = Yii::app()->user->id;

        $user = $this->loadModel($id, array(
            'assertPost' => true,
            'assertRole' => 'user.editAlias',
        ));

        $alias          = new User_Alias;
        $alias->alias   = Arr::getDot($_REQUEST, array('alias', 'User_Alias.alias'));
        $alias->user_id = $user->id;
        if (!$alias->save())
            throw new CHttpException(500, 'Save failure: ' . print_r($alias->errors, true));

        $this->redirect(array('user/view', 'id' => $id), true, 303);
    }

    public function actionRemoveAlias($alias, $id = null)
    {
        if (null === $id)
            $id = Yii::app()->user->id;

        $user = $this->loadModel($id, array(
            'assertPost' => true,
            'assertRole' => 'user.editAlias',
        ));

        $alias = User_Alias::model()->findByPk($alias);
        if (!$alias)
            throw new CHttpException(404);

        $alias->delete();
        $this->redirect(array('user/view', 'id' => $user->id), true, 303);
    }

    public function actionAddProject($project, $id = null)
    {
        if (null === $id)
            $id = Yii::app()->user->id;

        $user = $this->loadModel($id, array(
            'assertPost' => true,
            'assertRole' => 'user.editProject',
        ));

        $map  = new Project_User;
        $map->user_id = $user->id;
        $map->project_name = $project;
        if (!$map->save()) {
            Yii::app()->user->setFlash('error', Html::dl_errors($map));
        } else {
            Yii::app()->user->setFlash('success', 'Successfully added to project');
        }
        $this->redirect(array('user/view', 'id' => $id), true, 303);
    }
    public function actionRemoveProject($id, $project)
    {

    }

    public function actionLoginAs($id)
    {
        Yii::app()->user->requireAccess('admin');

        $user     = $this->loadModel($id);
        $identity = new UserIdentity($user->email, $user->password);
        $identity->forceAuthenticate($user);
        Yii::app()->user->login($identity);
        Yii::app()->user->setFlash('success', 'Login as ' . $user->display_name . ' successful.');
        $this->redirect(Yii::app()->homeUrl);
    }

    public function actionSettings($id = null)
    {
        $user = $this->view->user      = User::getUser($id);
        $form = $this->view->formModel = User_SettingForm::loadFromUser($user);

        if ($user && !empty($_POST['User_SettingForm'])) {
            $form->attributes = $_POST['User_SettingForm'];
            if ($form->validate()) {
                User_Setting::model()->deleteAllByAttributes(array(
                    'user_id' => $user->id,
                ));
                foreach ($form->attributes as $name => $value) {
                    $setting = new User_Setting;
                    $setting->user_id = $user->id;
                    $setting->setting = $name;
                    $setting->value   = $value;
                    $setting->save();
                }
                Yii::app()->user->setFlash('success', 'Settings have been saved.');
                $this->redirect(array('user/view', 'id' => $user->id));
            }
        }
    }
}

protected/views/user/_alias_form.php
<?php $user_alias = new User_Alias; ?>
<?php /** @var BootActiveForm $form */
$form  = $this->beginWidget('bootstrap.widgets.BootActiveForm', array(
    'type' => 'inline',
    'action' => array('user/addAlias', 'id' => $user->primaryKey),
    'htmlOptions'=>array('class'=>'well'),
)); ?>

<?php echo CHtml::hiddenField('User_Alias[user_id]', $user->primaryKey) ?>
<?php echo $form->textFieldRow($user_alias, 'alias', array('class'=>'span3')); ?>

<?php $this->widget('bootstrap.widgets.BootButton', array(
    'buttonType'=>'submit',
    'type'=>'primary',
    'icon'=>'arrow-right white',
    'label'=>'Add Alias')); ?>

<?php $this->endWidget(); ?>

protected/views/user/_comment.php
    <div style="font-size: 11px;"><?php echo Yii::app()->format->datetime($comment->created) ?></div>
    <div><a style="font-size: 11px;"><?php echo CHtml::link("{$comment->subject->project}: {$comment->subject->commit}", array(
        'review/view',
        'project' => $comment->subject->project,
        'commit'  => $comment->subject->commit
    )) ?></a></div>
    <div class="well well-small">
        <?php echo CHtml::encode($comment->comment) ?>
    </div>
    <?php if ($comment->actions): ?>
    <?php foreach ($comment->actions as $field => $values): ?>
        <em>
            <i class="icon-flag"></i>
            <?php echo sprintf('%s changed from "%s" to "%s"',
                    ucfirst(CHtml::encode($field)),
                    CHtml::encode($values['old']),
                    CHtml::encode($values['new'])) ?>
        </em>
    <?php endforeach ?>
    <?php endif ?>

protected/views/user/_form.php
<div class="form">
<?php /** @var BootActiveForm $form */
$form  = $this->beginWidget('bootstrap.widgets.BootActiveForm', array(
    'type'        => 'horizontal',
    'htmlOptions' => array('class'=>'well'),
)); ?>

<?php echo $form->textFieldRow($user, 'display_name', array('prepend'=>'<i class="icon-user"></i>','class'=>'span3')); ?>
<?php echo $form->textFieldRow($user, 'email', array('prepend'=>'<i class="icon-envelope"></i>','class'=>'span3')); ?>
<?php $user->password = Arr::getDot($_POST, 'User.password') ?>
<?php echo $form->passwordFieldRow(
        $user,
        'password',
        array(
            'class'=>'span3',
            'hint' => $user->isNewRecord ? null : 'Leave password blank to not change it.',
        )); ?>
<?php echo CHtml::hiddenField('User[projects]', '') // so de-selecting all projects fires a save ?>
<?php echo $form->dropDownListRow(
        $user,
        'projects',
        CHtml::listData(Project::model()->findAll(), 'name', 'name'),
        array('multiple'=>true, 'class'=>'project-list')); ?>
<?php Yii::app()->clientScript->registerScript('project-list', '
        $.each(' . CJSON::encode(CHtml::listData($user->projects, 'name', 'name')) .', function(key, value){
            $(".project-list option[value=\"" + value + "\"]").attr("selected", "selected");
        });
') ?>
<?php if (Yii::app()->user->checkAccess('admin')): ?>
    <?php echo $form->checkBoxRow($user, 'status'); ?>
    <?php echo $form->checkBoxListRow(
            $user,
            'roles',
            User::getConstants('ROLE_'),
            array(
                'hint' => '<strong>Note:</strong> Checking "admin" authorizes all other roles.',
            )); ?>
<?php endif ?>

<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.BootButton', array(
        'buttonType'=>'submit',
        'type'=>'primary',
        'icon'=>'ok white',
        'label'=>$user->isNewRecord ? 'Create' : 'Save')); ?>
    <?php $this->widget('bootstrap.widgets.BootButton', array(
        'buttonType'=>'reset',
        'icon'=>'remove',
        'label'=>'Reset')); ?>
</div>
<?php $this->endWidget(); ?>
</div>

protected/views/user/_settings_form.php
<div class="form">
<?php /** @var BootActiveForm $form */
$form  = $this->beginWidget('bootstrap.widgets.BootActiveForm', array(
    'type'        => 'horizontal',
    'htmlOptions' => array('class'=>'well'),
)); ?>

<?php echo $form->checkboxRow($formModel, 'email_myCodeReviewed'); ?>
<?php echo $form->checkboxRow($formModel, 'email_myReviewCommented'); ?>


<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.BootButton', array(
        'buttonType'=>'submit',
        'type'=>'primary',
        'icon'=>'ok white',
        'label'=>$user->isNewRecord ? 'Create' : 'Save')); ?>
    <?php $this->widget('bootstrap.widgets.BootButton', array(
        'buttonType'=>'reset',
        'icon'=>'remove',
        'label'=>'Reset')); ?>
</div>
<?php $this->endWidget(); ?>
</div>

protected/views/user/create.php
<?php
$this->breadcrumbs['Users'] = array('user/list');
$this->breadcrumbs[] = 'Add New User';
?>

<h1>Add New User:</h1>

<?php include '_form.php'; ?>

protected/views/user/list.php
<?php $this->breadcrumbs[] = 'Users' ?>

<h1>
    Users:
    <?php echo CHtml::link('&plus; new', array('user/create'), array('class' => 'btn btn-mini btn-primary')) ?>
</h1>
<?php $this->widget('bootstrap.widgets.BootGridView', array(
    'dataProvider'=>$users->search(),
    'filter' => $users,
    'template'=>"{items}\n{pager}",
    'columns'=>array(
        'display_name',
        'email',
//        'roles',
//        array(
//            'class' => 'CLinkColumn',
//            'id'=>'email',
//            'labelExpression' => 'CHtml::encode($data->email)',
//            'urlExpression'   => 'array("user/view", "id" => $data->primaryKey)',
//            'header'=>'Email',
//        ),
        'status:boolean',
        'last_login:datetime',
        array(
            'class'=>'bootstrap.widgets.BootButtonColumn',
            'htmlOptions'=>array('style'=>'width: 50px'),
        ),
    ),
)); ?>

protected/views/user/settings.php
<?php
$this->breadcrumbs['Users'] = array('user/list');
$this->breadcrumbs[CHtml::encode($user->email)] = array('user/view', 'id' => $user->primaryKey);
$this->breadcrumbs[] = 'Settings';
?>

<h1>Settings:</h1>

<?php include '_settings_form.php'; ?>

protected/views/user/update.php
<?php
$this->breadcrumbs['Users'] = array('user/list');
$this->breadcrumbs[CHtml::encode($user->email)] = array('user/view', 'id' => $user->primaryKey);
$this->breadcrumbs[] = 'Edit';
?>

<h1>Edit User:</h1>

<?php include '_form.php'; ?>

protected/views/user/view.php
<?php
$this->breadcrumbs['Users'] = array('user/list');
$this->breadcrumbs[] = CHtml::encode($user->email);
?>

<div class="row">
    <div class="span10">
        <?php $this->widget('bootstrap.widgets.BootDetailView', array(
            'data'=>$user,
            'attributes' => array(
                'display_name',
                'email',
                'status:boolean',
                'created:datetime',
                'updated:datetime',
                'last_login:datetime',
                'last_ip',
                array(
                    'label' => 'Roles',
                    'value' => implode(", ", (array) $user->roles),
                ),
                array(
                    'label' => 'Projects',
                    'value' => CHtml::encode(implode(", ", (array) CHtml::listData($user->projects, 'name', 'name'))),
                ),
            ),
        )); ?>
    </div>
    <div class="span2">
        <?php echo Html::gravitar($user->email, array(
            'default'     => 'mm',
            'size'        => 130,
            'htmlOptions' => array(
                'class' => 'thumbnail',
            ),
        )) ?>
        <?php if (Yii::app()->user->id == $user->id): ?>
        <?php echo CHtml::link('Change Gravatar', 'http://www.gravatar.com') ?>
        <?php endif ?>
    </div>
</div>

<div class="row">
    <div class="span12">
        <?php $this->widget('bootstrap.widgets.BootMenu', array(
            'type'  => 'pills', // '', 'tabs', 'pills' (or 'list')
            'items' => array(
                array(
                    'label'   => 'Settings',
                    'url'     => array('user/settings', 'id' => $user->primaryKey),
                    'icon'    => 'cog',
                    'visible' => Yii::app()->user->checkAccess('user.edit', $user),
                ), array(
                    'label'   => 'Edit User',
                    'url'     => array('user/update', 'id' => $user->primaryKey),
                    'icon'    => 'edit',
                    'visible' => Yii::app()->user->checkAccess('user.edit', $user),
                ), array(
                    'label'       => 'Delete User',
                    'url'         => array('user/delete', 'id' => $user->primaryKey),
                    'icon'        => 'trash',
                    'linkOptions' => array('class' => 'delete'),
                    'visible'     => Yii::app()->user->checkAccess('admin') && Yii::app()->user->id != $user->id,
                ), array(
                    'label'       => 'Login as User',
                    'url'         => array('user/loginAs', 'id' => $user->primaryKey),
                    'icon'        => 'eye-open',
                    'visible'     => Yii::app()->user->checkAccess('admin') && Yii::app()->user->id != $user->id,
                ),
            ),
        )); ?>
        <?php Yii::app()->clientScript->registerScript('deleteButton', '
            $("a.delete").on("click", function(e) {
                e.preventDefault();
                if (confirm("Are you sure you want to delete this User?")) {
                    $.post($(this).attr("href"), function(){
                        window.location.href = ' . CJSON::encode($this->createUrl('user/list')) . ';
                    });
                }
            });
        ') ?>
    </div>
</div>

<div class="row">
    <div class="span6">
        <h3>(Commit) Aliases:</h3>
        <ul class="unstyled well well-small">
            <?php foreach ($user->aliases as $alias): ?>
            <li class="user-alias">
                <i class="icon-user"></i>
                <?php echo CHtml::encode($alias->alias) ?>
                <div class="pull-right">
                <?php if (Yii::app()->user->checkAccess('user.edit', $user)): ?>
                <?php echo CHtml::link('<i class="icon-trash"></i>', array('user/removeAlias', 'alias' => $alias->alias)) ?>
                <?php endif ?>
                </div>
            </li>
            <?php endforeach; ?>
            <?php Yii::app()->clientScript->registerScript('user-alias-hover', '
                $("li.user-alias").css("padding", "2px;").hover(function(){
                        $(this).css("border-bottom", "1px dashed #999");
                    }, function(){
                        $(this).css("border-bottom", "1px dashed transparent");
                    }
                );
                ') ?>
        </ul>
        <?php if (Yii::app()->user->checkAccess('user.edit', $user)): ?>
        <?php include '_alias_form.php' ?>
        <?php endif ?>
    </div>
    <div class="span6">
        <h3>Recent Reviews:</h3>
        <ul>
            <?php foreach ($comments as $comment): ?>
            <li>
                <?php include '_comment.php' ?>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>